apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - httproute.yaml
  - n8n-secret-externalsecret.yaml
  - ns.yaml
  - pvc.yaml
  - service.yaml

namespace: n8n