apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: temporal
resources:
  - httproute.yaml
  - external-secret.yaml
  - secret-ready-gate.yaml
helmCharts:
  - name: temporal
    repo: https://go.temporal.io/helm-charts
    version: "1.2.0"
    releaseName: temporal
    namespace: temporal
    valuesFile: values.yaml
