persistence:
  enabled: true
  size: 10Gi
  storageClass: longhorn
service:
  http:
    type: ClusterIP
  ssh:
    type: ClusterIP
replicaCount: 1
valkey-cluster:
  enabled: false
postgresql-ha:
  enabled: false
postgresql:
  enabled: true