apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-mattshandev
  namespace: gateway
spec:
  dnsNames:
    - "*.mattshan.dev"
    - mattshan.dev
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-cluster-issuer
  secretName: cert-mattshandev
  usages:
    - digital signature
    - key encipherment