apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch-deployment
  namespace: karakeep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.11.1
          env:
            - name: MEILI_NO_ANALYTICS
              value: "true"
          volumeMounts:
            - mountPath: /meili_data
              name: meilisearch
          envFrom:
            - secretRef:
                name: karakeep-secrets
            - configMapRef:
                name: karakeep-config-map
          resources:
            requests:
              memory: "256Mi" # 256MB of memory
              cpu: "250m"     # .25 cpu cores
            limits:
              memory: "1Gi" # 1GB of memory
              cpu: "1000m" # 1 cpu core

      volumes:
        - name: meilisearch
          persistentVolumeClaim:
            claimName: meilisearch-pvc