apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  mattshan.server: |
    mattshan.dev:53 {
        errors
        cache 30
        forward . 192.168.1.107
    }