apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- config-map.yaml
- deployment.yaml
- service.yaml
- http-route.yaml
- pvc.yaml
- chrome/deployment.yaml
- chrome/service.yaml
- meillisearch/deployment.yaml
- meillisearch/pvc.yaml
- meillisearch/service.yaml

namespace: karakeep
