apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml
  - pvc.yaml
  - tcp-route.yaml
  - udp-route.yaml

namespace: minecraft