apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: minecraft-java-route
  namespace: minecraft
spec:
  parentRefs:
    - name: gateway-minecraft
      namespace: gateway
      port: 25565
    - name: gateway-minecraft
      namespace: gateway
      port: 19132
    - name: gateway-minecraft
      namespace: gateway
      port: 19133
  rules:
    - backendRefs:
        - name: minecraft
          port: 25565
        - name: minecraft
          port: 19132
        - name: minecraft
          port: 19133