apiVersion: v1
kind: ConfigMap
metadata:
  name: mc-bedrock-config
  namespace: mc-bedrock
  labels:
    role: service-config
    app: bds
data:
  # Find more options at https://github.com/itzg/docker-minecraft-bedrock-server#server-properties
  EULA: "true"
  GAMEMODE: "survival"
  DIFFICULTY: "easy"
  SERVER_NAME: "Minecraft Server"
  SERVER_PORT: "19132"
  MAX_PLAYERS: "10"
  PLAYER_IDLE_TIMEOUT: "30"
  TEXTUREPACK_REQUIRED: "false"
  ALLOW_LIST: "true"
  VIEW_DISTANCE: "10"
  TICK_DISTANCE: "4"
  MAX_THREADS: "8"
  DEFAULT_PLAYER_PERMISSION_LEVEL: "member"
  ALLOW_CHEATS: "true"
  MSA_GAMERTAGS_ONLY: "true"

  # ALLOW_LIST_USERS: "Canasian99:2535444275332904, WaffleStomp5:2535409901224971"
  # OPS: "Canasian99:2535444275332904, WaffleStomp5:2535409901224971"