apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-bedrock-pvc
  namespace: mc-bedrock
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi