apiVersion: v1
kind: Service
metadata:
  name: mc-bedrock-service
  namespace: mc-bedrock
spec:
  selector:
    app: bds
  ports:
    - port: 19132
      protocol: UDP
      nodePort: 30000
  type: NodePort