apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: herd-scheduler

resources:
  - ns.yaml
  - external-secret.yaml
  - migrate-job.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
