apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
spec:
  blocks:
    - cidr: "192.168.1.192/29"  # Provides usable IPs from 192.168.1.193 to 192.168.1.198
  allowFirstLastIPs: "No"  # Required in Cilium 1.16+ if reserving first/last IPs 
