apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud-auth-grafana-k8s-monitoring
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: grafana-cloud-auth-grafana-k8s-monitoring
    creationPolicy: Owner
  data:
    - secretKey: metricsUsername
      remoteRef:
        key: metrics-username
    - secretKey: logsUsername
      remoteRef:
        key: logs-username
    - secretKey: otlpUsername
      remoteRef:
        key: otlp-username
    - secretKey: password
      remoteRef:
        key: password
