apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml

helmCharts:
  - name: twingate-operator
    repo: oci://ghcr.io/twingate/helmcharts
    version: 0.29.0
    releaseName: twingate-operator
    namespace: twingate
    includeCRDs: true
    valuesFile: values.yaml
