apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: twingate-operator-auth
  namespace: twingate
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: twingate-operator-auth
    creationPolicy: Owner
  data:
    - secretKey: TWINGATE_API_KEY
      remoteRef:
        key: twingate-api-key
    - secretKey: TWINGATE_REMOTE_NETWORK_ID
      remoteRef:
        key: twingate-remote-network-id
