apiVersion: twingate.com/v1beta
kind: TwingateResourceAccess
metadata:
  name: homelab-users-n8n
  namespace: twingate
spec:
  groupRef:
    name: homelab-users
    namespace: twingate
  resourceRef:
    name: n8n-mattshan-dev
    namespace: twingate
---
apiVersion: twingate.com/v1beta
kind: TwingateResourceAccess
metadata:
  name: homelab-users-it-tools
  namespace: twingate
spec:
  groupRef:
    name: homelab-users
    namespace: twingate
  resourceRef:
    name: it-tools-mattshan-dev
    namespace: twingate